### ISSUE TITLE
Error --> custom_components/lelight/connector_bless.py:36

### ISSUE THREAD

**Issue by Kroate** [v1ack/lelight#2]
Hi folks,

can somebody say anything about my Error Log ??

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/lelight/connector_bless.py:36
Integration: LeLight (IRALAN) (documentation, issues)
First occurred: 12. November 2022 um 19:54:31 (22 occurrences)
Last logged: 10:07:45

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/lelight/connector_bless.py", line 62, in _send_message
    await self.server.send_message(message, timeout=0.25)
  File "/config/custom_components/lelight/connector_bless.py", line 36, in send_message
    await self.iface.call_register_advertisement(self.adv.path, {})  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/dbus_next/aio/proxy_object.py", line 92, in method_fn
    BaseProxyInterface._check_method_return(msg, intr_method.out_signature)
  File "/usr/local/lib/python3.10/site-packages/dbus_next/proxy_object.py", line 62, in _check_method_return
    raise DBusError._from_message(msg)
dbus_next.errors.DBusError: Failed to register advertisement


```

**Comment by Kroate** [comment]
Nobody any idea??

**Comment by v1ack** [comment]
How do you run home assistant?

**Comment by Kroate** [comment]
Hello v1ack

> How do you run home assistant?

Hassos on a RPI3+

Version: Home Assistant 2022.12.9

i hope you can help me

**Comment by caideone** [comment]
> 没人知道吗？？
大佬 你搞定没
