### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by caideone** [v1ack/lelight#4]
Logger: homeassistant
Source: custom_components/lelight/connector_bless.py:37
Integration: LeLight (IRALAN) ([documentation](https://github.com/v1ack/ha-lelight/README.md), [issues](https://github.com/v1ack/ha-lelight/issues))
First occurred: 22:41:58 (146 occurrences)
Last logged: 22:52:34

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/lelight/connector_bless.py", line 63, in _send_message
    await self.server.send_message(message, timeout=0.25)
  File "/config/custom_components/lelight/connector_bless.py", line 37, in send_message
    await self.iface.call_register_advertisement(self.adv.path, {})  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbus_next/aio/proxy_object.py", line 92, in method_fn
    BaseProxyInterface._check_method_return(msg, intr_method.out_signature)
  File "/usr/local/lib/python3.11/site-packages/dbus_next/proxy_object.py", line 62, in _check_method_return
    raise DBusError._from_message(msg)
dbus_next.errors.DBusError: Failed to parse advertisement.

**Comment by startarsyx** [comment]
in `connector_bless.py`:

modify:

```
self.adv._tx_power = 35
```

to:

```
self.adv._tx_power = -15
```

the error "Failed to parse advertisement" will be solved.

**Comment by caideone** [comment]
> 在`connector_bless.py`：
> 
> 调整：
> 
> ```
> self.adv._tx_power = 35
> ```
> 
> 到：
> 
> ```
> self.adv._tx_power = -15
> ```
> 
> “无法解析广告”的错误将会被解决。

thinks，but
None (<class 'custom_components.lelight.light.LeLight'>) sets invalid supported color modes {<ColorMode.ONOFF: 'onoff'>, <ColorMode.COLOR_TEMP: 'color_temp'>, <ColorMode.BRIGHTNESS: 'brightness'>}, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/v1ack/ha-lelight/issues
light is not working

**Comment by caideone** [comment]
https://github.com/user-attachments/assets/a5fe459a-0e6e-4e49-ac6a-ed1fd4d35457

已经可以控制
