### ISSUE TITLE
Alternative way to figure out the id?

### ISSUE THREAD

**Issue by Xanacas** [v1ack/lelight#5]
Hi There,
Is there an alternative way to figure out the device id?
Two out of three are not available in Apple App Store, the one that is available seems to require a chinese mobile phone number to open the app.
Can I use an ESP32 or something similar to send the command that discovers the device id?
If someone could help, I'm willing to pay for some help 🙏

**Comment by v1ack** [comment]
Theoretically - yes. But i don't know how.
Looks like it's easier to find an android phone, than to discover connecting algorithm

**Comment by caideone** [comment]
> 您好，请问 有其他方法可以获取设备 ID 吗？ 三分之二的应用程序在苹果应用商店中不可用，可用的似乎需要中国手机号码才能打开该应用程序。 我可以使用 ESP32 或类似的东西来发送发现设备 ID 的命令吗？ 如果有人能帮忙，我愿意支付一些帮助🙏


https://apps.apple.com/at/app/%E4%B9%90%E6%99%BA%E5%85%89/id1516073472
我通过厂家提供的网关，可以通过涂鸦智能生活将lemesh light 集成到homeassistant

**Comment by caideone** [comment]
此错误来自自定义集成。

Logger: homeassistant
Source: custom_components/lelight/connector_bless.py:37
Integration: LeLight (IRALAN) (documentation, issues)
First occurred: 20:39:47 (26 occurrences)
Last logged: 20:40:00

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/lelight/connector_bless.py", line 63, in _send_message
    await self.server.send_message(message, timeout=0.25)
  File "/config/custom_components/lelight/connector_bless.py", line 37, in send_message
    await self.iface.call_register_advertisement(self.adv.path, {})  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dbus_next/aio/proxy_object.py", line 92, in method_fn
    BaseProxyInterface._check_method_return(msg, intr_method.out_signature)
  File "/usr/local/lib/python3.12/site-packages/dbus_next/proxy_object.py", line 62, in _check_method_return
    raise DBusError._from_message(msg)
dbus_next.errors.DBusError: Failed to parse advertisement.

**Comment by caideone** [comment]
> 你好，还有 其他方法可以找出设备 ID 吗？ 三种方法中有两种在 Apple App Store 中不可用，可用的方法似乎需要中国手机号码才能打开应用程序。 我可以使用 ESP32 或类似的东西来发送发现设备 ID 的命令吗？ 如果有人能帮忙，我愿意付钱寻求帮助🙏

你有没有搞定
